backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: "static/images"
public_folder: "images"
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Draft', name: 'draft', widget: 'boolean' , default: 'true' }
      - { label: 'Tags', name: 'tags', widget: 'string' , default: "['','']" }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'top level'
    label: 'Top Level Pages'
    folder: 'content/'
    create: true
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
